// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/data.proto

package com.assignment.serviceone;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.assignment.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    boolean hasAge();
    /**
     * <code>required int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>required double salary = 3;</code>
     * @return Whether the salary field is set.
     */
    boolean hasSalary();
    /**
     * <code>required double salary = 3;</code>
     * @return The salary.
     */
    double getSalary();

    /**
     * <code>optional string dob = 4;</code>
     * @return Whether the dob field is set.
     */
    boolean hasDob();
    /**
     * <code>optional string dob = 4;</code>
     * @return The dob.
     */
    java.lang.String getDob();
    /**
     * <code>optional string dob = 4;</code>
     * @return The bytes for dob.
     */
    com.google.protobuf.ByteString
        getDobBytes();

    /**
     * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
     * @return Whether the saveType field is set.
     */
    boolean hasSaveType();
    /**
     * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
     * @return The saveType.
     */
    com.assignment.serviceone.PersonProto.Person.SaveContent getSaveType();
    /**
     * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
     */
    com.assignment.serviceone.PersonProto.Person.SaveContentOrBuilder getSaveTypeOrBuilder();
  }
  /**
   * Protobuf type {@code com.assignment.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.assignment.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      dob_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Person(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              age_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              salary_ = input.readDouble();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              dob_ = bs;
              break;
            }
            case 42: {
              com.assignment.serviceone.PersonProto.Person.SaveContent.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) != 0)) {
                subBuilder = saveType_.toBuilder();
              }
              saveType_ = input.readMessage(com.assignment.serviceone.PersonProto.Person.SaveContent.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(saveType_);
                saveType_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.assignment.serviceone.PersonProto.Person.class, com.assignment.serviceone.PersonProto.Person.Builder.class);
    }

    /**
     * Protobuf enum {@code com.assignment.Person.FileType}
     */
    public enum FileType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CSV = 0;</code>
       */
      CSV(0),
      /**
       * <code>XML = 1;</code>
       */
      XML(1),
      ;

      /**
       * <code>CSV = 0;</code>
       */
      public static final int CSV_VALUE = 0;
      /**
       * <code>XML = 1;</code>
       */
      public static final int XML_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static FileType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static FileType forNumber(int value) {
        switch (value) {
          case 0: return CSV;
          case 1: return XML;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FileType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          FileType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FileType>() {
              public FileType findValueByNumber(int number) {
                return FileType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.assignment.serviceone.PersonProto.Person.getDescriptor().getEnumTypes().get(0);
      }

      private static final FileType[] VALUES = values();

      public static FileType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private FileType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.assignment.Person.FileType)
    }

    public interface SaveContentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.assignment.Person.SaveContent)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .com.assignment.Person.FileType fileType = 1 [default = CSV];</code>
       * @return Whether the fileType field is set.
       */
      boolean hasFileType();
      /**
       * <code>required .com.assignment.Person.FileType fileType = 1 [default = CSV];</code>
       * @return The fileType.
       */
      com.assignment.serviceone.PersonProto.Person.FileType getFileType();
    }
    /**
     * Protobuf type {@code com.assignment.Person.SaveContent}
     */
    public static final class SaveContent extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.assignment.Person.SaveContent)
        SaveContentOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use SaveContent.newBuilder() to construct.
      private SaveContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private SaveContent() {
        fileType_ = 0;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new SaveContent();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private SaveContent(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int rawValue = input.readEnum();
                  @SuppressWarnings("deprecation")
                com.assignment.serviceone.PersonProto.Person.FileType value = com.assignment.serviceone.PersonProto.Person.FileType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  fileType_ = rawValue;
                }
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_SaveContent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_SaveContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.assignment.serviceone.PersonProto.Person.SaveContent.class, com.assignment.serviceone.PersonProto.Person.SaveContent.Builder.class);
      }

      private int bitField0_;
      public static final int FILETYPE_FIELD_NUMBER = 1;
      private int fileType_;
      /**
       * <code>required .com.assignment.Person.FileType fileType = 1 [default = CSV];</code>
       * @return Whether the fileType field is set.
       */
      @java.lang.Override public boolean hasFileType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .com.assignment.Person.FileType fileType = 1 [default = CSV];</code>
       * @return The fileType.
       */
      @java.lang.Override public com.assignment.serviceone.PersonProto.Person.FileType getFileType() {
        @SuppressWarnings("deprecation")
        com.assignment.serviceone.PersonProto.Person.FileType result = com.assignment.serviceone.PersonProto.Person.FileType.valueOf(fileType_);
        return result == null ? com.assignment.serviceone.PersonProto.Person.FileType.CSV : result;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasFileType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeEnum(1, fileType_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, fileType_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.assignment.serviceone.PersonProto.Person.SaveContent)) {
          return super.equals(obj);
        }
        com.assignment.serviceone.PersonProto.Person.SaveContent other = (com.assignment.serviceone.PersonProto.Person.SaveContent) obj;

        if (hasFileType() != other.hasFileType()) return false;
        if (hasFileType()) {
          if (fileType_ != other.fileType_) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasFileType()) {
          hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
          hash = (53 * hash) + fileType_;
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.assignment.serviceone.PersonProto.Person.SaveContent parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.assignment.serviceone.PersonProto.Person.SaveContent prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.assignment.Person.SaveContent}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.assignment.Person.SaveContent)
          com.assignment.serviceone.PersonProto.Person.SaveContentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_SaveContent_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_SaveContent_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.assignment.serviceone.PersonProto.Person.SaveContent.class, com.assignment.serviceone.PersonProto.Person.SaveContent.Builder.class);
        }

        // Construct using com.assignment.serviceone.PersonProto.Person.SaveContent.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          fileType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_SaveContent_descriptor;
        }

        @java.lang.Override
        public com.assignment.serviceone.PersonProto.Person.SaveContent getDefaultInstanceForType() {
          return com.assignment.serviceone.PersonProto.Person.SaveContent.getDefaultInstance();
        }

        @java.lang.Override
        public com.assignment.serviceone.PersonProto.Person.SaveContent build() {
          com.assignment.serviceone.PersonProto.Person.SaveContent result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.assignment.serviceone.PersonProto.Person.SaveContent buildPartial() {
          com.assignment.serviceone.PersonProto.Person.SaveContent result = new com.assignment.serviceone.PersonProto.Person.SaveContent(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.fileType_ = fileType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.assignment.serviceone.PersonProto.Person.SaveContent) {
            return mergeFrom((com.assignment.serviceone.PersonProto.Person.SaveContent)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.assignment.serviceone.PersonProto.Person.SaveContent other) {
          if (other == com.assignment.serviceone.PersonProto.Person.SaveContent.getDefaultInstance()) return this;
          if (other.hasFileType()) {
            setFileType(other.getFileType());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasFileType()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.assignment.serviceone.PersonProto.Person.SaveContent parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.assignment.serviceone.PersonProto.Person.SaveContent) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int fileType_ = 0;
        /**
         * <code>required .com.assignment.Person.FileType fileType = 1 [default = CSV];</code>
         * @return Whether the fileType field is set.
         */
        @java.lang.Override public boolean hasFileType() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required .com.assignment.Person.FileType fileType = 1 [default = CSV];</code>
         * @return The fileType.
         */
        @java.lang.Override
        public com.assignment.serviceone.PersonProto.Person.FileType getFileType() {
          @SuppressWarnings("deprecation")
          com.assignment.serviceone.PersonProto.Person.FileType result = com.assignment.serviceone.PersonProto.Person.FileType.valueOf(fileType_);
          return result == null ? com.assignment.serviceone.PersonProto.Person.FileType.CSV : result;
        }
        /**
         * <code>required .com.assignment.Person.FileType fileType = 1 [default = CSV];</code>
         * @param value The fileType to set.
         * @return This builder for chaining.
         */
        public Builder setFileType(com.assignment.serviceone.PersonProto.Person.FileType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          fileType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required .com.assignment.Person.FileType fileType = 1 [default = CSV];</code>
         * @return This builder for chaining.
         */
        public Builder clearFileType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          fileType_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.assignment.Person.SaveContent)
      }

      // @@protoc_insertion_point(class_scope:com.assignment.Person.SaveContent)
      private static final com.assignment.serviceone.PersonProto.Person.SaveContent DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.assignment.serviceone.PersonProto.Person.SaveContent();
      }

      public static com.assignment.serviceone.PersonProto.Person.SaveContent getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<SaveContent>
          PARSER = new com.google.protobuf.AbstractParser<SaveContent>() {
        @java.lang.Override
        public SaveContent parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SaveContent(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<SaveContent> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<SaveContent> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.assignment.serviceone.PersonProto.Person.SaveContent getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>required int32 age = 2;</code>
     * @return Whether the age field is set.
     */
    @java.lang.Override
    public boolean hasAge() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int SALARY_FIELD_NUMBER = 3;
    private double salary_;
    /**
     * <code>required double salary = 3;</code>
     * @return Whether the salary field is set.
     */
    @java.lang.Override
    public boolean hasSalary() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double salary = 3;</code>
     * @return The salary.
     */
    @java.lang.Override
    public double getSalary() {
      return salary_;
    }

    public static final int DOB_FIELD_NUMBER = 4;
    private volatile java.lang.Object dob_;
    /**
     * <code>optional string dob = 4;</code>
     * @return Whether the dob field is set.
     */
    @java.lang.Override
    public boolean hasDob() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string dob = 4;</code>
     * @return The dob.
     */
    @java.lang.Override
    public java.lang.String getDob() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dob_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string dob = 4;</code>
     * @return The bytes for dob.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDobBytes() {
      java.lang.Object ref = dob_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SAVETYPE_FIELD_NUMBER = 5;
    private com.assignment.serviceone.PersonProto.Person.SaveContent saveType_;
    /**
     * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
     * @return Whether the saveType field is set.
     */
    @java.lang.Override
    public boolean hasSaveType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
     * @return The saveType.
     */
    @java.lang.Override
    public com.assignment.serviceone.PersonProto.Person.SaveContent getSaveType() {
      return saveType_ == null ? com.assignment.serviceone.PersonProto.Person.SaveContent.getDefaultInstance() : saveType_;
    }
    /**
     * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
     */
    @java.lang.Override
    public com.assignment.serviceone.PersonProto.Person.SaveContentOrBuilder getSaveTypeOrBuilder() {
      return saveType_ == null ? com.assignment.serviceone.PersonProto.Person.SaveContent.getDefaultInstance() : saveType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAge()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSalary()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSaveType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSaveType().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, salary_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dob_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeMessage(5, getSaveType());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, salary_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dob_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getSaveType());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.assignment.serviceone.PersonProto.Person)) {
        return super.equals(obj);
      }
      com.assignment.serviceone.PersonProto.Person other = (com.assignment.serviceone.PersonProto.Person) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAge() != other.hasAge()) return false;
      if (hasAge()) {
        if (getAge()
            != other.getAge()) return false;
      }
      if (hasSalary() != other.hasSalary()) return false;
      if (hasSalary()) {
        if (java.lang.Double.doubleToLongBits(getSalary())
            != java.lang.Double.doubleToLongBits(
                other.getSalary())) return false;
      }
      if (hasDob() != other.hasDob()) return false;
      if (hasDob()) {
        if (!getDob()
            .equals(other.getDob())) return false;
      }
      if (hasSaveType() != other.hasSaveType()) return false;
      if (hasSaveType()) {
        if (!getSaveType()
            .equals(other.getSaveType())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAge()) {
        hash = (37 * hash) + AGE_FIELD_NUMBER;
        hash = (53 * hash) + getAge();
      }
      if (hasSalary()) {
        hash = (37 * hash) + SALARY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSalary()));
      }
      if (hasDob()) {
        hash = (37 * hash) + DOB_FIELD_NUMBER;
        hash = (53 * hash) + getDob().hashCode();
      }
      if (hasSaveType()) {
        hash = (37 * hash) + SAVETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSaveType().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.assignment.serviceone.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.assignment.serviceone.PersonProto.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.assignment.serviceone.PersonProto.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.assignment.serviceone.PersonProto.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.assignment.serviceone.PersonProto.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.assignment.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.assignment.Person)
        com.assignment.serviceone.PersonProto.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.assignment.serviceone.PersonProto.Person.class, com.assignment.serviceone.PersonProto.Person.Builder.class);
      }

      // Construct using com.assignment.serviceone.PersonProto.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSaveTypeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        salary_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        dob_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (saveTypeBuilder_ == null) {
          saveType_ = null;
        } else {
          saveTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.assignment.serviceone.PersonProto.internal_static_com_assignment_Person_descriptor;
      }

      @java.lang.Override
      public com.assignment.serviceone.PersonProto.Person getDefaultInstanceForType() {
        return com.assignment.serviceone.PersonProto.Person.getDefaultInstance();
      }

      @java.lang.Override
      public com.assignment.serviceone.PersonProto.Person build() {
        com.assignment.serviceone.PersonProto.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.assignment.serviceone.PersonProto.Person buildPartial() {
        com.assignment.serviceone.PersonProto.Person result = new com.assignment.serviceone.PersonProto.Person(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.age_ = age_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.salary_ = salary_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dob_ = dob_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          if (saveTypeBuilder_ == null) {
            result.saveType_ = saveType_;
          } else {
            result.saveType_ = saveTypeBuilder_.build();
          }
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.assignment.serviceone.PersonProto.Person) {
          return mergeFrom((com.assignment.serviceone.PersonProto.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.assignment.serviceone.PersonProto.Person other) {
        if (other == com.assignment.serviceone.PersonProto.Person.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAge()) {
          setAge(other.getAge());
        }
        if (other.hasSalary()) {
          setSalary(other.getSalary());
        }
        if (other.hasDob()) {
          bitField0_ |= 0x00000008;
          dob_ = other.dob_;
          onChanged();
        }
        if (other.hasSaveType()) {
          mergeSaveType(other.getSaveType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasName()) {
          return false;
        }
        if (!hasAge()) {
          return false;
        }
        if (!hasSalary()) {
          return false;
        }
        if (!hasSaveType()) {
          return false;
        }
        if (!getSaveType().isInitialized()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.assignment.serviceone.PersonProto.Person parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.assignment.serviceone.PersonProto.Person) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>required int32 age = 2;</code>
       * @return Whether the age field is set.
       */
      @java.lang.Override
      public boolean hasAge() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <code>required int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        bitField0_ |= 0x00000002;
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        bitField0_ = (bitField0_ & ~0x00000002);
        age_ = 0;
        onChanged();
        return this;
      }

      private double salary_ ;
      /**
       * <code>required double salary = 3;</code>
       * @return Whether the salary field is set.
       */
      @java.lang.Override
      public boolean hasSalary() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double salary = 3;</code>
       * @return The salary.
       */
      @java.lang.Override
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>required double salary = 3;</code>
       * @param value The salary to set.
       * @return This builder for chaining.
       */
      public Builder setSalary(double value) {
        bitField0_ |= 0x00000004;
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double salary = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSalary() {
        bitField0_ = (bitField0_ & ~0x00000004);
        salary_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object dob_ = "";
      /**
       * <code>optional string dob = 4;</code>
       * @return Whether the dob field is set.
       */
      public boolean hasDob() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string dob = 4;</code>
       * @return The dob.
       */
      public java.lang.String getDob() {
        java.lang.Object ref = dob_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            dob_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string dob = 4;</code>
       * @return The bytes for dob.
       */
      public com.google.protobuf.ByteString
          getDobBytes() {
        java.lang.Object ref = dob_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dob_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string dob = 4;</code>
       * @param value The dob to set.
       * @return This builder for chaining.
       */
      public Builder setDob(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dob_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string dob = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDob() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dob_ = getDefaultInstance().getDob();
        onChanged();
        return this;
      }
      /**
       * <code>optional string dob = 4;</code>
       * @param value The bytes for dob to set.
       * @return This builder for chaining.
       */
      public Builder setDobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dob_ = value;
        onChanged();
        return this;
      }

      private com.assignment.serviceone.PersonProto.Person.SaveContent saveType_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.assignment.serviceone.PersonProto.Person.SaveContent, com.assignment.serviceone.PersonProto.Person.SaveContent.Builder, com.assignment.serviceone.PersonProto.Person.SaveContentOrBuilder> saveTypeBuilder_;
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       * @return Whether the saveType field is set.
       */
      public boolean hasSaveType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       * @return The saveType.
       */
      public com.assignment.serviceone.PersonProto.Person.SaveContent getSaveType() {
        if (saveTypeBuilder_ == null) {
          return saveType_ == null ? com.assignment.serviceone.PersonProto.Person.SaveContent.getDefaultInstance() : saveType_;
        } else {
          return saveTypeBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       */
      public Builder setSaveType(com.assignment.serviceone.PersonProto.Person.SaveContent value) {
        if (saveTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          saveType_ = value;
          onChanged();
        } else {
          saveTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       */
      public Builder setSaveType(
          com.assignment.serviceone.PersonProto.Person.SaveContent.Builder builderForValue) {
        if (saveTypeBuilder_ == null) {
          saveType_ = builderForValue.build();
          onChanged();
        } else {
          saveTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       */
      public Builder mergeSaveType(com.assignment.serviceone.PersonProto.Person.SaveContent value) {
        if (saveTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
              saveType_ != null &&
              saveType_ != com.assignment.serviceone.PersonProto.Person.SaveContent.getDefaultInstance()) {
            saveType_ =
              com.assignment.serviceone.PersonProto.Person.SaveContent.newBuilder(saveType_).mergeFrom(value).buildPartial();
          } else {
            saveType_ = value;
          }
          onChanged();
        } else {
          saveTypeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       */
      public Builder clearSaveType() {
        if (saveTypeBuilder_ == null) {
          saveType_ = null;
          onChanged();
        } else {
          saveTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       */
      public com.assignment.serviceone.PersonProto.Person.SaveContent.Builder getSaveTypeBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSaveTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       */
      public com.assignment.serviceone.PersonProto.Person.SaveContentOrBuilder getSaveTypeOrBuilder() {
        if (saveTypeBuilder_ != null) {
          return saveTypeBuilder_.getMessageOrBuilder();
        } else {
          return saveType_ == null ?
              com.assignment.serviceone.PersonProto.Person.SaveContent.getDefaultInstance() : saveType_;
        }
      }
      /**
       * <code>required .com.assignment.Person.SaveContent saveType = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.assignment.serviceone.PersonProto.Person.SaveContent, com.assignment.serviceone.PersonProto.Person.SaveContent.Builder, com.assignment.serviceone.PersonProto.Person.SaveContentOrBuilder> 
          getSaveTypeFieldBuilder() {
        if (saveTypeBuilder_ == null) {
          saveTypeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.assignment.serviceone.PersonProto.Person.SaveContent, com.assignment.serviceone.PersonProto.Person.SaveContent.Builder, com.assignment.serviceone.PersonProto.Person.SaveContentOrBuilder>(
                  getSaveType(),
                  getParentForChildren(),
                  isClean());
          saveType_ = null;
        }
        return saveTypeBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.assignment.Person)
    }

    // @@protoc_insertion_point(class_scope:com.assignment.Person)
    private static final com.assignment.serviceone.PersonProto.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.assignment.serviceone.PersonProto.Person();
    }

    public static com.assignment.serviceone.PersonProto.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Person(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.assignment.serviceone.PersonProto.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_assignment_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_assignment_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_assignment_Person_SaveContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_assignment_Person_SaveContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024resources/data.proto\022\016com.assignment\"\333" +
      "\001\n\006Person\022\014\n\004name\030\001 \002(\t\022\013\n\003age\030\002 \002(\005\022\016\n\006" +
      "salary\030\003 \002(\001\022\013\n\003dob\030\004 \001(\t\0224\n\010saveType\030\005 " +
      "\002(\0132\".com.assignment.Person.SaveContent\032" +
      "E\n\013SaveContent\0226\n\010fileType\030\001 \002(\0162\037.com.a" +
      "ssignment.Person.FileType:\003CSV\"\034\n\010FileTy" +
      "pe\022\007\n\003CSV\020\000\022\007\n\003XML\020\001B(\n\031com.assignment.s" +
      "erviceoneB\013PersonProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_assignment_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_assignment_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_assignment_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Salary", "Dob", "SaveType", });
    internal_static_com_assignment_Person_SaveContent_descriptor =
      internal_static_com_assignment_Person_descriptor.getNestedTypes().get(0);
    internal_static_com_assignment_Person_SaveContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_assignment_Person_SaveContent_descriptor,
        new java.lang.String[] { "FileType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
